### ISSUE TITLE
Implement Intel Leaf=07h Subleaf=01h

### ISSUE THREAD

**Issue by Borketh** [gz/rust-cpuid#158]
https://en.wikipedia.org/wiki/CPUID#EAX=7,_ECX=1:_Extended_Features

Willing to try my hand at doing it myself - I need the avx_vnni flag in my project.

**Comment by AstroFloof** [comment]
Not to be confused with https://en.wikipedia.org/wiki/CPUID#EAX=80000021h:_Extended_Feature_Identification_2, which could be a separate issue if someone needs that.

**Comment by gz** [comment]
Definitely, feel free to send a PR. Otherwise we'll have to wait until I get around upgrading it. Currently the crate is at the SDM state from ~2018 for Intel CPUs.

**Comment by mert-kurttutan** [comment]
should be closed by #182
