### ISSUE TITLE
Update cpuid on crates.io

### ISSUE THREAD

**Issue by sunfishcode** [gz/rust-cpuid#17]
I have a [report](https://github.com/cretonne/cretonne/issues/302) of raw-cpuid not building on MSVC. It looks like [this is now fixed](https://github.com/gz/rust-cpuid/pull/10), but the fix is not yet published to crates.io. Would it be possible to publish a new version?

**Comment by gz** [comment]
I released version 3.1.0 on crates.io. Let me know if it doesn't fix the issue.

**Comment by sunfishcode** [comment]
Thanks!
