### ISSUE TITLE
Cache Size

### ISSUE THREAD

**Issue by mert-kurttutan** [gz/rust-cpuid#183]
Hi,
I could not find any function to get cache size in a reliable way. I am aware of the cacheinfo api, but all the solutions I am aware are rather hacky, and dependent on the cpu-specific info (whether it is modern/old cpu)

**Comment by gz** [comment]
Have you looked at this https://github.com/gz/rust-cpuid/blob/master/examples/cache.rs

As far as I'm aware there are several different ways in CPUID to get the cache size. Some newer and some older methods. You'll have to pick what's best for your architecture.

**Comment by mert-kurttutan** [comment]
Thanks, that seems to work OK.
