### ISSUE TITLE
Migrate to std::arch?

### ISSUE THREAD

**Issue by gnzlbg** [gz/rust-cpuid#19]
`std::arch::{x86, x86_64}` provides:

* [`__cpuid_count`](https://doc.rust-lang.org/nightly/core/arch/x86/fn.__cpuid_count.html)
* [`__cpuid`](https://doc.rust-lang.org/nightly/core/arch/x86/fn.__cpuid.html)
* [`__get_cpuid_max`](https://doc.rust-lang.org/nightly/core/arch/x86/fn.__get_cpuid_max.html)
* [`has_cpuid`](https://doc.rust-lang.org/nightly/core/arch/x86/fn.has_cpuid.html) 

By using these instead of inline assembly or C code the library will work on stable and not require a C compiler.

**Comment by gz** [comment]
I think we can close this now.
