### ISSUE TITLE
raw-cpuid 4.0.0 depends on heavyweight serde crate

### ISSUE THREAD

**Issue by ColinFinck** [gz/rust-cpuid#27]
raw-cpuid is advertised as "A library to parse the x86 CPUID instruction, written in rust with no external dependencies" and until 3.1.0, this was the case.

However, the recent 4.0.0 release added a dependency to the heavyweight "serde" crate.
While that was an optional feature when introduced by @alex-mckenna in ef3a6f5614e3c85d378df43c3e748d79f6794134, it quietly became a hard dependency in 686a7c5e6956b018985d9e4c704deefd1f848b3a by @gz 

Please make "serde" optional again in a subsequent release to keep raw-cpuid a small and universal crate.

**Comment by gz** [comment]
Hi, just for clarification what do you consider heavy-weight? You can (or should) still compile raw-cpuid for no_std environments even with serde. 

To clarify, I'm ok with making serde optional if there is good reason for it. My change was mostly because I didn't want unnecessary complexity due to feature pollution since serde does compile just fine for no_std and we only use it for trait derivations.

**Comment by lachlansneff** [comment]
I've been having issues with serde compiling incorrectly when using this on a no_std environment. Please move it back.

**Comment by gz** [comment]
Thanks for reporting this. I released cpuid 5.0 on which makes serde an optional dependcy again.
I'd be curious to know what breaks for you when using serde on no_std (maybe we should report it to serde itself. 

But it may be best to require for all dependencies to always be optional for this particular crate...

**Comment by ColinFinck** [comment]
Thanks for the prompt reply!
While I haven't witnessed actual build problems, the build time for my Rust-based kernel doubled with raw-cpuid 4.0.0 due to the "serde" dependency and all other packages it depends on.
Will try version 5.0.

**Comment by phil-opp** [comment]
@gz

> I'd be curious to know what breaks for you when using serde on no_std

I had a similar issue reported at rust-osdev/cargo-xbuild: https://github.com/rust-osdev/cargo-xbuild/issues/10. After some investigation it seems like it is a cargo issue: https://github.com/rust-lang/cargo/issues/5730

**Comment by gz** [comment]
@phil-opp Thanks that's good to know!
