### ISSUE TITLE
Compile Problems with Mac OS

### ISSUE THREAD

**Issue by beschaef** [gz/rust-cpuid#28]
Hello Guys,

We are actually developing a small own OS in rust.
https://github.com/beschaef/rtos

Currently we are testing ist under Mac OS. But we get the following error when we try to compile it.

= note: lld: error: undefined symbol: cpuid

          >>> referenced by lib.rs:32 (/Users/philippschultheiss/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-5.0.0/src/lib.rs:32)

          >>>               raw_cpuid-e9487655fe8e7103.raw_cpuid5.rcgu.o:(raw_cpuid::native_cpuid::cpuid_count::heb590b374d42c7b3) in archive /Users/philippschultheiss/Desktop/rtos/target/x86_64-rtos/debug/deps/libraw_cpuid-e9487655fe8e7103.rlib

The Error messages show the raw_cpuid Crate, but we are not shure if this really is a raw_cpuid problem, because it's running in your travis. 
Have you an idea what we are doing wrong or how to fix it? It seems only to be a mac problem

best regards,

Benny

**Comment by gz** [comment]
Can you give some more background, what rust compiler you are using what version of raw_cpuid, any enabled features for the compilation? Did you do a clean before the build?

**Comment by gz** [comment]
Closed since I'm unable to reproduce, please re-open if this still affects your build.
