### ISSUE TITLE
Add function to check for ABM

### ISSUE THREAD

**Issue by soc** [gz/rust-cpuid#30]
Hi Gerd!

(I'm not sure whether it makes sense to have this bug exist separately to #26, but I think this issue has a way smaller scope and may be fixable without needing to solve #26.)

According to https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets, availability of the `lzcount` instruction is indicated by the ABM flag:

> Intel uses AMD's ABM flag to indicate LZCNT support (since LZCNT completes the ABM)

It would be really useful to have a function available to check for ABM, even if the details differ slightly (there are Intel CPUs that support `popcnt` instructions, but not `lzcnt` instructions; while AMD added support for both at the same time).

As there seems no requirement to add a distinction between Intel and AMD for this, maybe this check could be added independently of what's decided in #26?

Please let me know if I can help!

Cheers,

Simon

**Comment by gz** [comment]
Hi -- Sorry for the late reply. 

Yes I'm ok with that for now; feel free to submit a pull request. Ideally I get some time this summer to implement AMD support (it will likely be a major release anyways since the current API can't accomodate both easily)..

**Comment by gz** [comment]
Hi this should be fixed with added AMD support (now in master). Feel free to re-open or make a new issue if this is still a problem.

**Comment by soc** [comment]
@gz Thanks a lot Gerd, I will try and integrate this new functionality and let you know how it worked out!
