### ISSUE TITLE
rustversion::stable means examples don't compile on beta

### ISSUE THREAD

**Issue by Mark-Simulacrum** [gz/rust-cpuid#35]
The Rust project has 3 release channels: stable, beta, and nightly. I am unsure if just adding another function with rustversion::beta would work here, but it would be nice to fix this.

https://github.com/gz/rust-cpuid/blob/master/examples/tsc_frequency.rs#L17

I noted this while triaging the crater report for beta, but this is not new afaict.

**Comment by dtolnay** [comment]
`#[rustversion::nightly]` + `#[rustversion::not(nightly)]` seems to be the intention in the code.

**Comment by gz** [comment]
@dtolnay Agreed, I didn't realize this is possible to express with rustversion at the time. Will update accordingly...

**Comment by gz** [comment]
Fixed and released as 8.1.2
