### ISSUE TITLE
Backport `into_iter` -> `iter` fix to 7.0.x?

### ISSUE THREAD

**Issue by LukasKalbertodt** [gz/rust-cpuid#37]
Hi there!

Do you think you could backport [this fix](https://github.com/gz/rust-cpuid/commit/7c14795980e19815854074f0ee3877d1ab15f4c2) to version 7 and release it as 7.0.4? At least judging by the downloads on `crates.io`, most crates seem to depend on `raw-cpuid = "7"` still. It would help a lot with `https://github.com/rust-lang/rust/pull/65819` if the fix could be released for 7. Thanks for your consideration :)

**Comment by gz** [comment]
Hi, Sure I release 7.0.4 with the fix.

**Comment by LukasKalbertodt** [comment]
Thanks a bunch :)
