### ISSUE TITLE
Maybe wrong result of Hypervisor Info?

### ISSUE THREAD

**Issue by phip1611** [gz/rust-cpuid#52]
Hi! I'm having a `x86_64` UEFI machine with an Intel i5-10600k as CPU that runs the latest Windows 10. The `HYPERVISOR`-flag in the CPU features is - as expected - not set but `.hypervisor_info()` still returns something. Do you know why this happens? Is there a bug in this library or is the operating system doing strange things?

The value I receive is `(4800, 100, 0)` (ebx, ecx, edx).

On another machine of mine (notebook running Ubuntu) `CpuId::get_hypervisor_info()` doesn't return anything as expected, because I'm not in a virtualized environment.

**Comment by gz** [comment]
Hm it's not quite clear if this check here is the right approach: https://github.com/gz/rust-cpuid/blob/10a6648c1eaa76e765e2287a91307ddc558a176a/src/lib.rs#L605

Maybe instead Bit 31 of ECX of CPUID leaf 0x1 should be used and if not set, return None...

```
Hypervisor Present Bit:
        Bit 31 of ECX of CPUID leaf 0x1.

        This bit has been reserved by Intel & AMD for use by
        hypervisors, and indicates the presence of a hypervisor.

        Virtual CPU's (hypervisors) set this bit to 1 and physical CPU's
        (all existing and future cpu's) set this bit to zero.  This bit
	can be probed by the guest software to detect whether they are
	running inside a virtual machine.
```
Source: https://lwn.net/Articles/301888/

**Comment by phip1611** [comment]
> Maybe instead Bit 31 of ECX of CPUID leaf 0x1 should be used and if not set, return None...

Sounds reasonable, but I'm not deep enough into the subject to be 100% sure.

**Comment by phip1611** [comment]
@gz If you want, I could prepare this in a PR. What do you think?

PS: What's your plan for the v10 release?

**Comment by gz** [comment]
Hi yes that might be a good idea. We can probably test it easily on qemu/kvm/esx to see if it breaks something that would cover a lot.

For v10, ideally we can also add AMD support. The extended leafs (>0x80000000) arent inplemented for AMD yet, but I'll spend some time on it this weekend and see how far I get! This may lead to more breaking changes for the API but I am not sure yet.
