### ISSUE TITLE
Publish new release on crates.io

### ISSUE THREAD

**Issue by ahmedcharles** [gz/rust-cpuid#7]
It would be convenient to have a release with the recent fix for QEMU supporting 10 extended function info banks. Thanks.

**Comment by gz** [comment]
Hi, sure which commit are you referring to?

**Comment by ahmedcharles** [comment]
https://github.com/gz/rust-cpuid/commit/c3ebfc553cdff98d19d29777fd85c4f9182bfb66

**Comment by gz** [comment]
With some delay (sorry for that) I release 2.0.2 today which includes the patch.
