### ISSUE TITLE
path to use on stable Rust?

### ISSUE THREAD

**Issue by BurntSushi** [gz/rust-cpuid#8]
I think it would be great if this crate could be made to work on stable Rust. As far as I can see, there are two nightly-only features being used: `prelude_import` and `asm`. I don't think `prelude_import` is being used. Indeed, if I remove it, the crate still compiles and passes tests.

Getting rid of the `asm` feature is trickier. But, there's not that much Assembly, and it seems like it should be possible to write the Assembly in their own `.S` files and then link them in using `build.rs`. You can see an example of that working here: https://github.com/alexcrichton/stacker

Would you be open to such a strategy? If so, I'd be happy to try and do the leg work on this!

**Comment by gz** [comment]
Hi, yes I think getting this crate into stable would be very useful!

**Comment by gz** [comment]
I released version 3.0 which includes tones patch. Thanks!

**Comment by BurntSushi** [comment]
@gz thanks! :)

**Comment by gz** [comment]
Sorry it took so long. I was travelling for the last 3 weeks. But now I'm back.
